

POST http://localhost:8000/api/events/68276aa0db5de912d59a8ee9/create
Content-Type: application/json

{
"category_id": "507f1f77bcf86cd799439011",
"date": "2023-12-15T10:00:00",
"location": "Москва, ул. Пушкина 10",
"name": "Конференция по Python"
}