POST http://localhost:8000/api/users/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456",
  "name": "Test User"
}

###

GET http://localhost:8000/api/users/test@test.com

###